select * from customer limit 20


--Total revenue generated by male vs, female customers

select gender  , sum(purchase_amount) as revenue
from customer
group by gender

-- Customers that used a discount but still spent more than the average purchase amount
select customer_id , purchase_amount 
from customer 
where discount_applied = 'Yes' and  purchase_amount >= (select avg(purchase_amount) from customer)

-- TOP 5 products with the highest average review rating 
select item_purchased as product , ROUND(avg(review_rating::numeric),2) as "Average product Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;

-- Compare the average Purchase amounts between standard and express shipping
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount::numeric), 2) AS "Average Purchase Amount"
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do Subscribed customers spend more ? Compare  average spend and total revenue between subscribers and non-subscribers
select subscription_status , 
count(customer_id) as total_customer , 
ROUND(avg(purchase_amount),2) as average_spend  , 
Round(sum(purchase_amount),2) as total_revenue 
from customer 
group by subscription_status
order by total_revenue , average_spend desc ; 

-- the 5 products have the highest percentage of purchases with discounts applied
select item_purchased , 
ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Segmet Customers into New returning , and Loyal based on their total nmber of previous purchase 
-- and show the count of each segment

with customer_type as (
select customer_id , previous_purchases , 
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	Else 'Loyal'
	End as customer_segment
from customer
)
select customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- top 3 most purchased products within cateory
with item_counts as (
select category  , item_purchased , count(customer_id) as total_orders , 
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category , item_purchased

)
 select item_rank , category , item_purchased , total_orders 
 from item_counts
 where item_rank <= 3 ; 
-- are customers  who  are repeat buyers (more than 5 previous purchased ) also likely to subscribe
select subscription_status , count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--  the revenue contribution of each age group
select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group
order by   total_revenue desc ; 







